import {
  ICON_USER,
  ICON_EDIT,
  ICON_SOCIAL_LINKS,
  ICON_LINK,
  ICON_RESUME,
  ICON_FOLDER,
  ICON_EDUCATION,
  ICON_BOOK,
  ICON_EXPERIENCE,
  ICON_BUILDING,
  ICON_STARS,
  ICON_HAND_SPARKLES,
  ICON_EEO,
  ICON_INFO,
  ICON_OTHER_DETAILS,
  ICON_PEN_RULER,
} from '@/utils/icons'

export const infoCards = [
  {
    title: 'Personal Info',
    description: 'Name, Email, Phone, Address',
    color: '#3B82F6',
    icon: ICON_USER,
    actionIcon: ICON_EDIT,
    dialog: 'personalInfo',
  },
  {
    title: 'Social Profiles',
    description: 'LinkedIn, Portfolio, Github',
    color: '#3B82F6',
    // color: '#F59E0B',
    icon: ICON_SOCIAL_LINKS,
    actionIcon: ICON_LINK,
    dialog: 'socialProfiles',
  },
  {
    title: 'Resume',
    description: 'Upload your latest resume',
    color: '#3B82F6',
    // color: '#22C55E',
    icon: ICON_RESUME,
    actionIcon: ICON_FOLDER,
    dialog: 'resume',
  },
  {
    title: 'Education',
    description: 'Degree, School, Graduation Year',
    color: '#3B82F6',
    // color: '#C084FC',
    icon: ICON_EDUCATION,
    actionIcon: ICON_BOOK,
    dialog: 'education',
  },
  {
    title: 'Experience',
    description: 'Previous jobs and roles',
    color: '#3B82F6',
    icon: ICON_EXPERIENCE,
    actionIcon: ICON_BUILDING,
    dialog: 'experience',
  },
  {
    title: 'Skills',
    description: 'List your key skills',
    color: '#3B82F6',
    // color: '#F59E0B',
    icon: ICON_STARS,
    actionIcon: ICON_HAND_SPARKLES,
    dialog: 'skills',
  },
  {
    title: 'EEO Info',
    description: 'Race, Gender, Veteran Status',
    color: '#3B82F6',
    // color: '#22C55E',
    icon: ICON_EEO,
    actionIcon: ICON_INFO,
    dialog: 'eeoInfo',
  },
  {
    title: 'Other Details',
    description: 'Salary, Work Authorization, etc.',
    color: '#3B82F6',
    // color: '#C084FC',
    icon: ICON_OTHER_DETAILS,
    actionIcon: ICON_PEN_RULER,
    dialog: 'otherDetails',
  },
]
