export const RELATIVE_MATCHES = {
  degreeType: [
    ['associate', 'associates', "associate's", 'aa'],
    ['bachelor', 'bachelors', "bachelor's", 'bs'],
    ['master', 'masters', "master's", 'ms'],
    ['doctorate', 'phd', 'ph.d'],
  ],
  country: [
    ['us', 'usa', 'united states', 'united states of america', 'america'],
    ['ca', 'can', 'canada'],
    ['gb', 'gbr', 'uk', 'united kingdom', 'great britain', 'britain', 'england'],
    ['au', 'aus', 'australia'],
    ['de', 'deu', 'germany'],
    ['fr', 'fra', 'france'],
    ['es', 'esp', 'spain'],
    ['it', 'ita', 'italy'],
    ['cn', 'chn', 'china', "people's republic of china"],
    ['jp', 'jpn', 'japan'],
    ['in', 'ind', 'india'],
    ['br', 'bra', 'brazil'],
    ['mx', 'mex', 'mexico'],
    ['nl', 'nld', 'netherlands', 'the netherlands'],
    ['kr', 'kor', 'south korea', 'korea', 'republic of korea'],
    ['ru', 'rus', 'russia', 'russian federation'],
    ['ch', 'che', 'switzerland'],
    ['se', 'swe', 'sweden'],
    ['pl', 'pol', 'poland'],
    ['ie', 'irl', 'ireland'],
    ['pt', 'prt', 'portugal'],
    ['ar', 'arg', 'argentina'],
    ['za', 'zaf', 'south africa'],
    ['sg', 'sgp', 'singapore'],
    ['nz', 'nzl', 'new zealand'],
  ],
  state: [
    ['al', 'ala', 'alabama'],
    ['ak', 'alaska'],
    ['az', 'ariz', 'arizona'],
    ['ar', 'ark', 'arkansas'],
    ['ca', 'calif', 'california'],
    ['co', 'colo', 'colorado'],
    ['ct', 'conn', 'connecticut'],
    ['de', 'del', 'delaware'],
    ['fl', 'fla', 'florida'],
    ['ga', 'georgia'],
    ['hi', 'hawaii'],
    ['id', 'idaho'],
    ['il', 'ill', 'illinois'],
    ['in', 'ind', 'indiana'],
    ['ia', 'iowa'],
    ['ks', 'kan', 'kans', 'kansas'],
    ['ky', 'ken', 'kentucky'],
    ['la', 'louisiana'],
    ['me', 'maine'],
    ['md', 'maryland'],
    ['ma', 'mass', 'massachusetts'],
    ['mi', 'mich', 'michigan'],
    ['mn', 'minn', 'minnesota'],
    ['ms', 'miss', 'mississippi'],
    ['mo', 'missouri'],
    ['mt', 'mont', 'montana'],
    ['ne', 'neb', 'nebr', 'nebraska'],
    ['nv', 'nev', 'nevada'],
    ['nh', 'new hampshire'],
    ['nj', 'new jersey'],
    ['nm', 'new mexico'],
    ['ny', 'new york'],
    ['nc', 'north carolina'],
    ['nd', 'north dakota'],
    ['oh', 'ohio'],
    ['ok', 'okla', 'oklahoma'],
    ['or', 'ore', 'oreg', 'oregon'],
    ['pa', 'penn', 'penna', 'pennsylvania'],
    ['ri', 'rhode island'],
    ['sc', 'south carolina'],
    ['sd', 'south dakota'],
    ['tn', 'tenn', 'tennessee'],
    ['tx', 'tex', 'texas'],
    ['ut', 'utah'],
    ['vt', 'vermont'],
    ['va', 'virginia'],
    ['wa', 'wash', 'washington'],
    ['wv', 'west virginia'],
    ['wi', 'wis', 'wisc', 'wisconsin'],
    ['wy', 'wyo', 'wyoming'],
  ],
}
